"""Capital flow sankey — daily $ → sector → ticker."""

from collections import defaultdict
from datetime import date, timedelta

from investment_journal.models.allocation import Allocation
from investment_journal.models.earnings_event import EarningsEvent


def _short_sector(s: str) -> str:
    return s.split("/")[0].strip()


def render_upcoming_earnings(
    events: list[tuple[EarningsEvent, int | None]],
    *,
    today: date,
    horizon_days: int = 90,
    repo: str | None = None,
) -> str:
    """Sorted table of upcoming earnings within `horizon_days`.

    `events` is a list of (EarningsEvent, issue_number) pairs. Events outside
    the [today, today+horizon] window are dropped. Sort key: (date, ticker).
    """
    horizon_end = today + timedelta(days=horizon_days)
    upcoming = sorted(
        [(e, n) for e, n in events if today <= e.expected_date <= horizon_end],
        key=lambda pair: (pair[0].expected_date, pair[0].ticker),
    )

    lines = [
        "# Upcoming earnings",
        "",
        "_Auto-generated by `scripts/render_upcoming_earnings.py` from open `earnings` issues. Do not edit by hand._",
        "",
        f"_Window: {today.isoformat()} → {horizon_end.isoformat()} ({horizon_days} days). Updated {today.isoformat()}._",
        "",
    ]
    if not upcoming:
        lines += ["_None scheduled in this window._", ""]
        return "\n".join(lines)

    lines += [
        "| Date | Ticker | Quarter | Timing | Issue |",
        "|---|---|---|---|---|",
    ]
    for e, n in upcoming:
        timing = "—" if e.timing == "unknown" else e.timing
        if n is None:
            ref = "—"
        elif repo:
            ref = f"[#{n}](https://github.com/{repo}/issues/{n})"
        else:
            ref = f"#{n}"
        lines.append(
            f"| {e.expected_date.isoformat()} | {e.ticker} | {e.quarter} | {timing} | {ref} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_capital_flow_sankey(allocation: Allocation) -> str:
    by_sector: dict[str, list] = defaultdict(list)
    for p in allocation.positions:
        by_sector[_short_sector(p.sector)].append(p)

    src = f"Daily ${allocation.dca.total_per_day_usd:g}"
    rows: list[str] = []
    for sec, ps in by_sector.items():
        rows.append(f"{src},{sec},{sum(p.dca_per_day_usd for p in ps):g}")
    for sec, ps in by_sector.items():
        for p in ps:
            rows.append(f"{sec},{p.ticker},{p.dca_per_day_usd:g}")
    sankey = "\n".join(rows)

    return f"""# Capital flow

_Auto-generated by `scripts/render_dashboards.py` from `portfolio/allocation.yml`. Do not edit by hand._

```mermaid
---
config:
  sankey:
    showValues: true
---
sankey-beta
{sankey}
```
"""
