"""Issue body renderers: model → GitHub issue markdown."""

from investment_journal.models.earnings_event import EarningsEvent
from investment_journal.models.horizon import HorizonPlan
from investment_journal.models.risk import Risk
from investment_journal.models.scenario import Scenario
from investment_journal.models.thesis_review import ThesisReview
from investment_journal.models.tone import DISCLAIMER
from investment_journal.models.watchlist import WatchlistEntry
from investment_journal.models.weekly_review import WeeklyReview


def _checkbox(label: str, checked: bool = False) -> str:
    return f"- [{'x' if checked else ' '}] {label}"


def render_risk_issue(risk: Risk) -> str:
    """Body of the GitHub issue tracking a single risk."""
    lines = [
        f"# {risk.id} — {risk.title}",
        "",
        f"_Severity:_ **{risk.severity}** &nbsp;•&nbsp; "
        f"_Ticker:_ **{risk.ticker or 'portfolio-level'}** &nbsp;•&nbsp; "
        f"_Surfaced in:_ `{risk.surfaced_in}` &nbsp;•&nbsp; "
        f"_Surfaced on:_ {risk.surfaced_on.isoformat()} &nbsp;•&nbsp; "
        f"_Status:_ **{risk.status}**",
        "",
        "## Description",
        "",
        risk.description.strip(),
        "",
        "## Monitor for",
        "",
        risk.monitor_for.strip(),
        "",
    ]

    if risk.status == "resolved":
        lines += [
            "## Resolution",
            "",
            f"_Resolved on:_ {risk.resolved_on.isoformat() if risk.resolved_on else '—'}",
            "",
            risk.resolution_note or "",
            "",
        ]

    lines += [
        "---",
        f"Source of truth: [`risks/{risk.id}.md`](../blob/main/risks/{risk.id}.md). Edit there, not here.",
        "",
        DISCLAIMER,
    ]
    return "\n".join(lines)


def render_risks_index(all_risks: list[Risk]) -> str:
    """Body of the pinned Risks Index issue. Regenerated whenever risks/R-*.md changes."""
    open_risks = [r for r in all_risks if r.status != "resolved"]
    resolved_risks = [r for r in all_risks if r.status == "resolved"]
    resolved_recent = sorted(
        resolved_risks, key=lambda r: r.resolved_on or r.surfaced_on, reverse=True
    )[:10]

    def _row(r: Risk) -> str:
        ref = f"#{r.issue_number}" if r.issue_number else r.id
        return (
            f"| `{r.id}` | {r.severity} | {r.ticker or '—'} | "
            f"{r.title} | `{r.surfaced_in}` | {ref} |"
        )

    lines = [
        "# Risks Index",
        "",
        "_Pinned. All open risks across positions, plus the most recently resolved._",
        "_Auto-generated by `.github/workflows/risks-index-sync.yml` from `risks/R-*.md`. Do not edit by hand._",
        "",
        f"## Open ({len(open_risks)})",
        "",
    ]
    if open_risks:
        lines += [
            "| ID | Severity | Ticker | Title | Surfaced in | Issue |",
            "|---|---|---|---|---|---|",
        ]
        # Sort: high → medium → low, then by surfaced_on descending.
        sev_order = {"high": 0, "medium": 1, "low": 2}
        for r in sorted(
            open_risks,
            key=lambda r: (sev_order[r.severity], -r.surfaced_on.toordinal()),
        ):
            lines.append(_row(r))
    else:
        lines.append("_No open risks._")

    lines += ["", f"## Recently resolved ({len(resolved_recent)})", ""]
    if resolved_recent:
        lines += [
            "| ID | Ticker | Resolved on | Title | Note | Issue |",
            "|---|---|---|---|---|---|",
        ]
        for r in resolved_recent:
            ref = f"#{r.issue_number}" if r.issue_number else r.id
            note = (
                (r.resolution_note or "").splitlines()[0] if r.resolution_note else "—"
            )
            lines.append(
                f"| `{r.id}` | {r.ticker or '—'} | "
                f"{r.resolved_on.isoformat() if r.resolved_on else '—'} | "
                f"{r.title} | {note} | {ref} |"
            )
    else:
        lines.append("_None yet._")

    lines += ["", "---", DISCLAIMER]
    return "\n".join(lines)


def render_weekly_review(
    wr: WeeklyReview, risks_lookup: dict[str, Risk] | None = None
) -> str:
    risks_lookup = risks_lookup or {}
    lines = [
        f"# Weekly review {wr.iso_week}",
        "",
        f"_Generated {wr.generated_on.isoformat()}._",
        "",
        "## Per-position update",
        "",
    ]
    for ticker, upd in wr.per_position.items():
        lines += [f"### {ticker}", ""]
        if upd.news_bullets:
            lines.append("**News (last 7d):**")
            lines.append("")
            for b in upd.news_bullets:
                lines.append(f"- {b}")
            lines.append("")
        lines += [
            f"**Valuation read:** {upd.valuation_line}",
            "",
            f"**Thesis status:** `{upd.thesis_status}` — {upd.thesis_status_note}",
            "",
            "---",
            "",
        ]

    lines += ["## Catalyst calendar (next 30 days)", ""]
    if wr.catalysts_30d:
        for c in sorted(wr.catalysts_30d, key=lambda c: c.when):
            link = f" — {c.issue_link}" if c.issue_link else ""
            lines.append(f"- {c.when.isoformat()}: **{c.ticker}** — {c.event}{link}")
    else:
        lines.append("_None._")

    lines += ["", "## Risks", ""]
    if wr.risks_surfaced:
        lines.append("**Surfaced this week:**")
        lines.append("")
        for rid in wr.risks_surfaced:
            r = risks_lookup.get(rid)
            if r and r.issue_number:
                lines.append(f"- [ ] #{r.issue_number} — {r.title}")
            else:
                lines.append(f"- [ ] `{rid}` (issue pending)")
        lines.append("")
    if wr.risks_resolved:
        lines.append("**Resolved this week:**")
        lines.append("")
        for rid in wr.risks_resolved:
            r = risks_lookup.get(rid)
            if r and r.issue_number:
                lines.append(f"- ~~#{r.issue_number}~~ — {r.title}")
            else:
                lines.append(f"- ~~`{rid}`~~")
        lines.append("")
    if not wr.risks_surfaced and not wr.risks_resolved:
        lines.append("_No risk changes this week._")
        lines.append("")

    lines += ["---", DISCLAIMER]
    return "\n".join(lines)


def render_thesis_review(
    tr: ThesisReview, risks_lookup: dict[str, Risk] | None = None
) -> str:
    risks_lookup = risks_lookup or {}
    lines = [
        f"# Thesis review: {tr.ticker} {tr.month}",
        "",
        f"Reviewing the thesis for **{tr.ticker}** for **{tr.month}**.",
        "",
        f"Dossier: [`portfolio/positions/{tr.ticker}.md`](../blob/main/portfolio/positions/{tr.ticker}.md)",
        "",
        "## Verdict",
        "",
        f"`{tr.verdict}` — {tr.verdict_note}",
        "",
        "## What changed in the bull case?",
        "",
        tr.bull_changes or "_(no change)_",
        "",
        "## What changed in the bear case / risks?",
        "",
        tr.bear_changes or "_(no change)_",
        "",
        "## Action taken or planned",
        "",
        tr.action,
        "",
        "## Risks",
        "",
    ]
    if tr.risks_surfaced:
        lines.append("**Surfaced:**")
        lines.append("")
        for rid in tr.risks_surfaced:
            r = risks_lookup.get(rid)
            ref = f"#{r.issue_number}" if r and r.issue_number else f"`{rid}`"
            title = r.title if r else "(pending)"
            lines.append(f"- [ ] {ref} — {title}")
        lines.append("")
    if tr.risks_resolved:
        lines.append("**Resolved:**")
        lines.append("")
        for rid in tr.risks_resolved:
            r = risks_lookup.get(rid)
            ref = f"#{r.issue_number}" if r and r.issue_number else f"`{rid}`"
            title = r.title if r else "(pending)"
            lines.append(f"- ~~{ref}~~ — {title}")
        lines.append("")
    if not tr.risks_surfaced and not tr.risks_resolved:
        lines.append("_No risk changes from this review._")
        lines.append("")

    lines += [
        "## Checklist",
        "",
        _checkbox("Position file thesis section updated"),
        _checkbox("`allocation.yml` updated (if weights changed)"),
        "",
        "---",
        DISCLAIMER,
    ]
    return "\n".join(lines)


def render_earnings_event(e: EarningsEvent) -> str:
    timing = "" if e.timing == "unknown" else f" ({e.timing})"
    lines = [
        f"# Earnings: {e.ticker} {e.quarter}",
        "",
        f"Expected: **{e.expected_date.isoformat()}**{timing}",
        "",
    ]
    if e.prep_notes:
        lines += ["## Prep notes", "", e.prep_notes.strip(), ""]
    lines += ["## Tracking checklist", ""]
    for item in e.checklist:
        lines.append(_checkbox(item))
    lines.append("")
    if e.recap:
        lines += [
            "## Recap",
            "",
            f"- **Reported:** {e.recap.revenue}; {e.recap.eps}",
            f"- **Guidance:** {e.recap.guidance}",
        ]
        if e.recap.call_quotes:
            lines.append("- **Call quotes:**")
            for q in e.recap.call_quotes:
                lines.append(f"  - > {q}")
        if e.recap.thesis_impact_pending:
            lines.append("- **Thesis impact:** pending human review.")
        if e.recap.sources:
            lines.append("- **Sources:**")
            for s in e.recap.sources:
                lines.append(f"  - {s}")
        lines.append("")
    lines += ["---", DISCLAIMER]
    return "\n".join(lines)


def render_watchlist_issue(entry: WatchlistEntry) -> str:
    """Body of the GitHub issue tracking a single watchlist candidate."""
    passed = entry.buckets_passed
    buckets = ["cash", "finance", "stability", "profitability"]
    badges = " ".join(f"**{b}** ✓" if b in passed else f"~~{b}~~" for b in buckets)
    lines = [
        f"# Watchlist: {entry.ticker} — {entry.name}",
        "",
        f"_Sector:_ {entry.sector} &nbsp;•&nbsp; "
        f"_Added:_ {entry.added_on.isoformat()} &nbsp;•&nbsp; "
        f"_Conviction:_ **{entry.conviction}** &nbsp;•&nbsp; "
        f"_Status:_ **{entry.status}**",
        "",
        f"Quality buckets: {badges}",
        "",
        "## Thesis note",
        "",
        entry.thesis_note.strip(),
        "",
        "## Quality screen",
        "",
        "| Bucket | Pass | Notes |",
        "|---|---|---|",
    ]
    for r in entry.screen_results:
        icon = "✓" if r.passed else "✗"
        note = (r.note or "").replace("|", "\\|")
        lines.append(f"| {r.bucket} | {icon} | {note} |")
    if not entry.screen_results:
        lines.append("| _(not yet screened)_ | — | — |")

    lines += [
        "",
        "## Decision checklist",
        "",
        _checkbox("Initial screen complete (all 4 buckets evaluated)"),
        _checkbox("Thesis note written with primary source citations"),
        _checkbox("All quality buckets pass"),
        _checkbox("Added to `portfolio/watchlist.yml`"),
        _checkbox("Scenario filed: watchlist trigger → add to portfolio"),
        "",
        "---",
        f"Source of truth: [`portfolio/watchlist.yml`](../blob/main/portfolio/watchlist.yml) — `{entry.ticker}` entry.",
        "",
        DISCLAIMER,
    ]
    return "\n".join(lines)


def render_scenario_issue(scenario: Scenario) -> str:
    """Body of the GitHub issue tracking a single scenario."""
    lines = [
        f"# {scenario.id} — {scenario.title}",
        "",
        f"_Type:_ **{scenario.trigger_type}** &nbsp;•&nbsp; "
        f"_Ticker:_ **{scenario.ticker or 'portfolio-level'}** &nbsp;•&nbsp; "
        f"_Status:_ **{scenario.status}**"
        + (
            f" (triggered {scenario.triggered_on.isoformat()})"
            if scenario.triggered_on
            else ""
        ),
        "",
        "## Trigger",
        "",
        scenario.trigger_description.strip(),
        "",
        "## Action",
        "",
        scenario.action_description.strip(),
        "",
    ]
    if scenario.context:
        lines += ["## Context", "", scenario.context.strip(), ""]
    if scenario.status == "resolved":
        lines += [
            "## Resolution",
            "",
            f"_Triggered:_ {scenario.triggered_on.isoformat() if scenario.triggered_on else '—'}",
            "",
            scenario.resolution_note or "",
            "",
        ]
    lines += [
        "---",
        f"Source of truth: [`portfolio/scenarios/{scenario.id}.md`](../blob/main/portfolio/scenarios/{scenario.id}.md). Edit there, not here.",
        "",
        DISCLAIMER,
    ]
    return "\n".join(lines)


def render_horizon_review(
    plan: HorizonPlan, scenarios: list[Scenario] | None = None
) -> str:
    """Body of the annual horizon review issue for the current phase."""
    scenarios = scenarios or []
    phase = plan.current_phase
    active_scenarios = [s for s in scenarios if s.status == "active"]
    triggered_scenarios = [s for s in scenarios if s.status == "triggered"]

    lines = [
        f"# Horizon review — Phase {phase.phase}: {phase.name}",
        "",
        f"_Horizon version:_ {plan.horizon_version} &nbsp;•&nbsp; "
        f"_Started:_ {plan.started_on.isoformat()} &nbsp;•&nbsp; "
        f"_Phase window:_ {phase.start.isoformat()} → {phase.end.isoformat()} &nbsp;•&nbsp; "
        f"_Daily DCA:_ ${plan.total_dca_per_day_usd:.0f}",
        "",
        "## Phase objective",
        "",
        phase.objective.strip(),
        "",
        "## Decision gates",
        "",
    ]
    for gate in phase.decision_gates:
        icon = "✓" if gate.answered else "○"
        lines.append(f"### {icon} {gate.question}")
        if gate.answered and gate.answer_note:
            lines += ["", gate.answer_note.strip(), ""]
        else:
            lines += ["", "_Not yet answered._", ""]

    lines += ["## Active scenarios", ""]
    if triggered_scenarios:
        lines.append("**Triggered (action required):**")
        lines.append("")
        for s in triggered_scenarios:
            ref = f"#{s.issue_number}" if s.issue_number else s.id
            lines.append(f"- 🔴 {ref} — {s.title} (`{s.trigger_type}`)")
        lines.append("")
    if active_scenarios:
        lines.append("**Monitoring:**")
        lines.append("")
        for s in active_scenarios:
            ref = f"#{s.issue_number}" if s.issue_number else s.id
            ticker = f"[{s.ticker}] " if s.ticker else ""
            lines.append(f"- {ref} — {ticker}{s.title} (`{s.trigger_type}`)")
        lines.append("")
    if not active_scenarios and not triggered_scenarios:
        lines.append("_No active scenarios._")
        lines.append("")

    lines += [
        "## Review checklist",
        "",
        _checkbox("Decision gates answered above"),
        _checkbox("Triggered scenarios actioned"),
        _checkbox("Watchlist reviewed for ready candidates"),
        _checkbox("Allocation weights reflect current conviction"),
        _checkbox("`portfolio/horizon_plan.yml` updated (gates marked answered)"),
        "",
        "---",
        DISCLAIMER,
    ]
    return "\n".join(lines)
